const Data = [
  {
    "id": 1,
    "candidate": "John",
    "subtitle": "Sr.Engineer",
    "referred": 30,
    "interviewed": 50,
    "hired": 70,
    "joined": 0,
    "reward": 3000,
  },
  {
    "id": 2,
    "candidate": "Priya",
    "subtitle": "Sr.Engineer",
    "referred": 10,
    "interviewed": 40,
    "hired": 0,
    "joined": 0,
    "reward": 3000,
  },
  {
    "id": 3,
    "candidate": "Harshita",
    "subtitle": "Sr.Engineer",
    "referred": 30,
    "interviewed": 50,
    "hired": 70,
    "joined": 100,
    "reward": 10000,
  },
  {
    "id": 4,
    "candidate": "John",
    "subtitle": "Sr.Engineer",
    "referred": 10,
    "interviewed": 0,
    "hired": 0,
    "joined": 0,
    "reward": 3000,
  },
  {  
     "id": 5,
      "candidate":"Vineet",
      "subtitle": "Sr.Engineer",
      "referred":30,
      "interviewed":50,
      "hired":70,
      "joined":100,
      "reward":3000,
  },
  {
      "id": 6,
      "candidate":"Sonali",
      "subtitle": "Sr.Engineer",
      "referred":30,
      "interviewed":40,
      "hired":0,
      "joined":0,
      "reward":2000,
  },
  {
      "id": 7,
      "candidate":"Kajal",
      "subtitle": "Sr.Engineer",
      "referred":30,
      "interviewed":50,
      "hired":70,
      "joined":0,
      "reward":5000,
  },
  {
      "id": 8,
      "candidate":"Mona",
      "subtitle": "Sr.Engineer",
      "referred":30,
      "interviewed":50,
      "hired":70,
      "joined":100,
      "reward":4000,
  },
  {
      "id": 9,
      "candidate":"Rekha",
      "subtitle": "Sr.Engineer",
      "referred":10,
      "interviewed":0,
      "hired":0,
      "joined":0,
      "reward":3000,
  }
];

export default Data;
